before:
  hooks:
    - go mod tidy
    - go generate ./...
builds:
  - id: kafka-canary
    main: ./cmd/kafka-canary
    ldflags: -X main.version={{.Version}}
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin # Only for local testing/development
snapshot:
  name_template: "{{ incpatch .Version }}.{{.ShortCommit}}-next"
