apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "kafka-canary.fullname" . }}
  labels:
    {{- include "kafka-canary.labels" . | nindent 4 }}
data:
  {{- if .Values.config }}
  config.yaml: |
    {{ .Values.config | toYaml | nindent 4 }}
  {{- end }}
